version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # ĐÃ FIX: Chui hẳn vào thư mục con, build cục bộ tại đó (.) để ăn khớp Context với Dockerfile gốc
      - cd my-web-app && docker build -t $REPOSITORY_URL:latest . && cd .&& cd . cd ...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL:latest
      - echo Copying deployment files to root...
      - cp my-web-app/appspec.yaml .
      - cp my-web-app/taskdef.json .
      - printf '[{"name":"web-container","imageUri":"%s"}]' $REPOSITORY_URL:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
