version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image using absolute path context...
      - docker build -t $REPOSITORY_URL:latest -f my-web-app/Dockerfile my-web-app/
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - echo Fetching real RDS endpoint address...
      # ĐÃ FIX CHỐT HẠ: Đổi tên identifier thành production-ecs-postgres cho khớp với hạ tầng
      - RDS_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier production-ecs-postgres --query "DBInstances[0].Endpoint.Address" --output text)
      - echo Writing image and DB definitions file...
      - sed -i "s|<IMAGE_PLACEHOLDER>|$REPOSITORY_URL:$IMAGE_TAG|g" my-web-app/taskdef.json
      - sed -i "s|<DB_HOST_PLACEHOLDER>|$RDS_ENDPOINT|g" my-web-app/taskdef.json

artifacts:
  files:
    - my-web-app/taskdef.json
    - my-web-app/appspec.yaml
  discard-paths: yes